### ISSUE TITLE
Missing status on order

### ISSUE THREAD

**Issue by Kashyap1999** [PensoPay/magento2-pensopay#3]
There is an issue with the order status in the Pensopay payment module. The order status is missing when placing the order. This issue occurs when the pensopay module is not configured and trying to place order. In the backend order will generate but there is a missing order status. 

**Screenshot-1**
![image](https://github.com/user-attachments/assets/47c26c50-a71e-4259-bacd-fb55523fa77e)

**Steps to Reproduce:**
1. Start with a clean Magento shop with sample data.
2. Install PensoPay Payment Module.
3. Enable module from
 Store > Settings > Configuration > Sales > Payment Methods > pensopay.
 (See screenshot-2)
4. go to frontend and try to make an order with the pensopay payment method.

Order is not completed in the frontend due to the module not configured. But in the backend order is created without any status.

**Screenshot-2**
![image](https://github.com/user-attachments/assets/f7b7fe89-fc22-44db-ad5f-9e6b389767e3)

**Expected Behavior**
If the order isn't completed, the order in the backend should have a default status or should be “New Order Status before Payment” which is configured in the configuration (see in screenshot-2).

**Actual Result**
There is no status on that order which is not completed.

**Additional information:**
I have checked this issue and found the event “sales_order_place_after” This event is responsible for setting the order status. which is triggered after the payment is authorized.

**Screenshot-3 (observer SalesOrderPlaceAfter)**
![image](https://github.com/user-attachments/assets/ebb90c6f-387f-46ff-8b14-9730da6799b9)

**Screenshot-4 (event.xml)**
![image](https://github.com/user-attachments/assets/fe6b1f7e-6420-4d03-a611-4a3f111e1173)

However, we noticed that other payment modules, like Viabill, or others. they set the order status before payment authorization.

To fix this, the event should be sales_order_place_before instead of sales_order_place_after. Using the sales_order_place_before event would ensure the order is created with the "New Order Status before Payment" even when the Pensopay module isn't configured.

**Comment by ghost** [comment]
Thank you for reporting this @Kashyap1999 
While we look into the fix, can you briefly explain in what circumstance this module would be installed but inactive, rather than it not existing at all in the project?

Thank you

**Comment by idmistir** [comment]
Fixed in 2.2.2. Thank you for reporting this
