### ISSUE TITLE
Card type image not showing on order confirmation page.

### ISSUE THREAD

**Issue by dhruvi-prajapat1** [PensoPay/magento2-pensopay#4]
When completing a payment using Mastercard Debet, the card type image does not appear on the order confirmation page.

**Screenshot-1:** order confirmation page
![image](https://github.com/user-attachments/assets/03c283b2-819e-4d36-8289-808c81f1f5b2)

**Steps to Reproduce:**
    1. Take a shop.
    2. Install “pensopay/magento2” module and run setup command.
    3. Order a product and make payment from mastercard-debet and send confirmation email.

**Expected Results:**
The card type image should display

**Actual Results:**
The card type image is not appearing.

**Additional Information:-** 
In the module at pensopay/magento2/view/base/web/images/pensopaypayment the filename mastercarddebet.png is incorrect.

**Solution:-**
The correct file name should be mastercard-debet.png

**Comment by idmistir** [comment]
Released 2.2.2 which fixes this. Thank you for reporting this.
